#!/usr/bin/python3
import os
import sys

# 获取脚本所在的目录
script_dir = os.path.dirname(os.path.realpath(__file__))
# 调用实际的 python 脚本
os.execv('/usr/bin/python3', ['python3', os.path.join(script_dir, 'video_web_server.py')] + sys.argv[1:])
